
services:
  db:
    image: mariadb:10.6
    container_name: mes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: motdepasserootrobuste1234
      MYSQL_DATABASE: mes4
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: ./backend
    container_name: mes_web
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
